package novalogics.android.shoppinglist.data.database.entity

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a shopping item entity for the "shopping_items" table.
 * The `id` is auto-generated by the database and is `null` until the item is inserted,
 * allowing object creation without providing an ID upfront.
 */
/**
 * Annotations:
 * - `@Entity`: Marks the class as a Room entity and specifies the table name.
 * - `@ColumnInfo`: Maps each property to a column in the database with a custom column name.
 * - `@PrimaryKey`: Marks the `id` as the primary key and enables auto-generation for unique IDs.
 */
@Entity(tableName = "shopping_items")
data class ShoppingItem(
    @ColumnInfo(name = "item_name")
    var name: String,

    @ColumnInfo(name = "item_amount")
    var amount: Int,
) {
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "item_id")
    var id: Int = 0
}
